name: mpcdl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - planetary-computer=1.0.0
  - pystac-client=0.9.0
  - pystac=1.10.0
  - stackstac=0.5.1
  - rasterio=1.4.3
  - rioxarray=0.19.0
  - xarray=2025.10.1
  - geopandas=1.1.1
  - shapely=2.1.2
  - pyproj=3.7.2
  - numpy=1.26.4
  - python-dotenv=1.1.1
  - requests
  - tqdm
  - pip
  - pip:
      - -e .
